### PR TITLE
Fixing content-type on combined JS file response

### PR DESCRIPTION
**Pull request by EricSeastrand**
Fixes issue #14

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Can you point this to devel instead of master please?

**Comment by EricSeastrand** [comment]
Updated

**Comment by peepsnet** [comment]
This fixed my issue in MagentoCE 1.9.3.2

This should be merged

**Comment by miguelbalparda** [comment]
Thank you for your contribution @willcodeforfood!

**Comment by TheRealJAG** [comment]
@miguelbalparda I'm still seeing this issue on Magento ver. 1.9.3.6

When I close the browser and go directly to the admin I see this: 
dashboard

I'm still able to browse around the admin. When I logged out, I don't see the error. 

I'm going to assume devel is not production ready.

**Pull request merged**
